### ISSUE TITLE
Application failed to start

### ISSUE THREAD

**Issue by Jeffix78** [amundi/onSiteManagement#4]
The application successfully compile, I got the .jar file
But there is an error on starting
Please find the message below

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

**Comment by FabriceGazin** [comment]
Hi Jeffix, 

The problem is the same as for this issue #3 
Basically, if you want to use the H2 embedded database, the H2 dependency should be in your classpath: take a look at the pom.xml file, that means that you have to activate 'local' profile.

I just committed a few changes, to activate this profil by default.

**Comment by Jeffix78** [comment]
Perfect, it's working
Thank you
